cpu:
  image: deephdc/deep-oc-dogs_breed_det:cpu
  ports:
    - 5000:5000
  entrypoint: deepaas-run --listen-ip=0.0.0.0

gpu:
  image: deephdc/deep-oc-dogs_breed_det
  ports:
    - 5000:5000
  entrypoint: deepaas-run --listen-ip=0.0.0.0

cpu-local:
  extends:
    service: cpu
  volumes:
    - $HOME/datasets/dogs_breed/data:/srv/dogs_breed_det/data
    - $HOME/datasets/dogs_breed/models:/srv/dogs_breed_det/models

gpu-local:
  extends:
    service: gpu
  volumes:
    - $HOME/datasets/dogs_breed/data:/srv/dogs_breed_det/data
    - $HOME/datasets/dogs_breed/models:/srv/dogs_breed_det/models

cpu-rclone:
  extends:
    service: cpu
  volumes:
    - $HOME/.config/rclone:/srv/rclone
  environment:
    - RCLONE_CONFIG=/srv/rclone/rclone.conf

